name: Deploy VoDan to Play Store & Github Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'app/**'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
        
      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
      
      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: com.origin.vodan
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal

      - name: Build APK
        run: flutter build apk --release

      - name: Create Github Release & Upload APK
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      